trigger: none

pool:
 vmImage: 'ubuntu-latest'



variables:
 buildConfiguration: 'Release'

resources:
  repositories:
  # - repository: MultiRepoBuild
  #   name: MultiRepoBuild
  #   type: git
  #   # trigger:
  #   # #  pr: 
  #   #     branches:
  #   #       include:
  #   #       - master 

    
  - repository: first_repository 
    type: GitHub 
    connection: myGitHubConnection
    source: adityahcl1/Maven 
    pr: 
      branches:
       include:
       - master 
  - repository: second_repository    
    type: GitHub 
    connection: myGitHubConnection
    source: adityahcl1/testing123 
    pr: 
       branches:
         include:
         - master

steps:
 - checkout: self
 - checkout: first_repository
 - checkout: second_repository
